### ISSUE TITLE
'Simulator' object has no attribute 'get_num_populations'

### ISSUE THREAD

**Issue by agladstein** [YingZhou001/popdemog#1]
Hi,

I'm trying out your package, and when I try your example in the tutorial to transform the msprime command to ms,
```
python msprime2ms.py demo1.py population_configurations migration_matrix demographic_events
```
I get this error:
```
Traceback (most recent call last):
  File "msprime2ms.py", line 40, in <module>
    N = simulator.get_num_populations()
AttributeError: 'Simulator' object has no attribute 'get_num_populations'
```

**Comment by YingZhou001** [comment]
Hi,

Sorry to reply so late.  I thought github would send me email but somehow I didn't receive any. 
It is the issue that msprime has been updated so the old converting program does not work.
With Xiaowen's help, I upload the new python script which should work.

Thanks,

Ying
